### ISSUE TITLE
Setting up for alacritty

### ISSUE THREAD

**Issue by RaZ0rr-Two** [eylles/vifm-sixel-preview#1]
I am sorry if this is a dumb question but how do I set this up for alacritty terminal?

I installed all pre requisites but I cannot get the preview. ~~It's not caching the image files in `~/.cache/vifm`~~. The images are being properly cached but its not showing in the preview pane.

**Comment by eylles** [comment]
that most likely has to do with sixel scrolling, `echo '\e[?80l'` should activate sixel scrolling and `echo '\e[?80h'` should turn it off, i've been going over it with xterm, i have tried to have it work inside the script but from my tests that needs to be ran before running vifm
